/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hakimcosmetique;

/**
 *
 * @author PC Click
 */
import java.sql.*;
import Project.ConnectionProvider;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
public class article extends javax.swing.JFrame {

    /**
     * Creates new form article
     */
    public article() {
        initComponents();
        updateArticleTable();
       // setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogAjouter = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jArticleTable = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column) {
                return false;
            };};
            jButton4 = new javax.swing.JButton();
            jButton5 = new javax.swing.JButton();
            jLabel9 = new javax.swing.JLabel();
            jTextField9 = new javax.swing.JTextField();

            jDialogAjouter.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            jDialogAjouter.setLocationByPlatform(true);
            jDialogAjouter.setMinimumSize(new java.awt.Dimension(500, 400));
            jDialogAjouter.setPreferredSize(new java.awt.Dimension(500, 400));

            jLabel2.setText("Marque");

            jTextField5.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField5ActionPerformed(evt);
                }
            });

            jTextField1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField1ActionPerformed(evt);
                }
            });

            jButton6.setText("Ajouter");
            jButton6.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton6ActionPerformed(evt);
                }
            });

            jLabel1.setText("Article");

            jLabel5.setText("Prix en detail");

            jLabel4.setText("Prix en gros ");

            jButton2.setText("Annuler");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jDialogAjouterLayout = new javax.swing.GroupLayout(jDialogAjouter.getContentPane());
            jDialogAjouter.getContentPane().setLayout(jDialogAjouterLayout);
            jDialogAjouterLayout.setHorizontalGroup(
                jDialogAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogAjouterLayout.createSequentialGroup()
                    .addGroup(jDialogAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDialogAjouterLayout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addGroup(jDialogAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addGap(82, 82, 82)
                            .addGroup(jDialogAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jDialogAjouterLayout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addGroup(jDialogAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jDialogAjouterLayout.createSequentialGroup()
                                    .addGroup(jDialogAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(66, 66, 66)
                                    .addGroup(jDialogAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jDialogAjouterLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton6)))))
                    .addContainerGap(246, Short.MAX_VALUE))
            );
            jDialogAjouterLayout.setVerticalGroup(
                jDialogAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogAjouterLayout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addGroup(jDialogAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGap(18, 18, 18)
                    .addGroup(jDialogAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jDialogAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(29, 29, 29)
                    .addGroup(jDialogAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGap(64, 64, 64)
                    .addGroup(jDialogAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton6)
                        .addComponent(jButton2))
                    .addContainerGap(93, Short.MAX_VALUE))
            );

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jButton1.setText("Retour");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });
            getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 480, -1, -1));

            jArticleTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Article", "Marque", "Prix en gros", "Prix en détail"
                }
            ) {
                boolean[] canEdit = new boolean [] {
                    false, false, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });
            jScrollPane1.setViewportView(jArticleTable);

            getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 450, 340));

            jButton4.setText("Supprimer");
            jButton4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton4ActionPerformed(evt);
                }
            });
            getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, -1, -1));

            jButton5.setText("Ajouter un nouveau Article");
            jButton5.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton5ActionPerformed(evt);
                }
            });
            getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, -1, -1));

            jLabel9.setText("Rechercher");
            getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

            jTextField9.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField9ActionPerformed(evt);
                }
            });
            jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    jTextField9KeyPressed(evt);
                }
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    jTextField9KeyReleased(evt);
                }
                public void keyTyped(java.awt.event.KeyEvent evt) {
                    jTextField9KeyTyped(evt);
                }
            });
            getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 280, -1));

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       jDialogAjouter.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String article = jTextField1.getText();
        String marque = jTextField2.getText();
        String prixgros = jTextField4.getText();
        String prixdetail = jTextField5.getText();
        try {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            Statement st2=con.createStatement();
            int id = -1;
            st.executeUpdate("insert into article(Article,marque,prixgros,prixdetail) values('"+article+"','"+marque+"','"+prixgros+"','"+prixdetail+"');");
            //getArticle id 
             ResultSet rs1= st2.executeQuery("select ArticleID from Article where Article='"+article+"' and marque='"+marque+"';");
           while(rs1.next()){ id=rs1.getInt("ArticleID");}
            //add to stock table (artID,0)
            Statement st3=con.createStatement();
            st3.executeUpdate("insert into stock(Articleid,qte) values('"+id+"','0');");

            jDialogAjouter.setVisible(false);
updateArticleTable();
        } catch (Exception e) { JOptionPane.showMessageDialog(null,"error!");
            System.out.println(e);
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       jDialogAjouter.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);        // TODO add your handling code here:
        new Stock().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
                try {
            Connection con=ConnectionProvider.getCon();
            int row = jArticleTable.getSelectedRow();
            
            String article=(jArticleTable.getModel().getValueAt(row, 0).toString());
            String marque=(jArticleTable.getModel().getValueAt(row, 1).toString());
           String prixGros=(jArticleTable.getModel().getValueAt(row, 2).toString());
           String prixDetail=(jArticleTable.getModel().getValueAt(row, 3).toString());
            int id=-1;
            Statement st3=con.createStatement();
            ResultSet rs1= st3.executeQuery("select ArticleID from Article where Article='"+article+"' and marque='"+marque+"';");
           while(rs1.next()){ id=rs1.getInt("ArticleID");}
            Statement st2=con.createStatement();
            st2.executeUpdate("Delete from stock where ArticleID='"+id+"';");
            Statement st=con.createStatement();
            st.executeUpdate("Delete from article where Article='"+article+"' and marque='"+marque+"'and prixGros='"+prixGros+"'and prixDetail='"+prixDetail+"';");
        
        } catch (Exception e) { 
        JOptionPane.showMessageDialog(null,"erreur!");
            System.out.println(e);
        }
       updateArticleTable();
                
                
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyPressed
        
                
        
        
    }//GEN-LAST:event_jTextField9KeyPressed

    private void jTextField9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyTyped
        
       
    }//GEN-LAST:event_jTextField9KeyTyped

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
       
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyReleased
         String rech=jTextField9.getText();
        
        try {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("Select Article,marque,prixGros,prixDetail from article where Article LIKE '"+rech+"%' or marque LIKE '"+rech+"%' ;");
        
            jArticleTable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) { 
        JOptionPane.showMessageDialog(null,"erreur!");
            System.out.println(e);
        }
    }//GEN-LAST:event_jTextField9KeyReleased

    
    
    public static void  updateArticleTable(){
try {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs= st.executeQuery("select Article,marque,prixGros,prixDetail from article;");
            jArticleTable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) { 
  System.out.println(e);
        }
}
public static int  getArticleCount(){
 try {
            Connection con1=ConnectionProvider.getCon();
            Statement st1=con1.createStatement();
            ResultSet rs1= st1.executeQuery("select count(*) AS total from Article;");
           
           while(rs1.next()){
    return rs1.getInt("total");
    
    }
        } catch (Exception e) { 
  System.out.println("err");
        }
return 0;
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(article.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(article.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(article.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(article.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new article().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTable jArticleTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JDialog jDialogAjouter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
